---
apiVersion: v1
kind: Service
metadata:
  name: rainbowdarkness-service
spec:
  selector:
    app: rainbowdarkness-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002