---
apiVersion: v1
kind: Service
metadata:
  name: rainbowdarkness-server-service
  labels:
    job: rainbowdarkness-server-service-job
    app: rainbowdarkness-server-service-app
spec:
  selector:
    app: rainbowdarkness-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
      name: rainbowdarkness-server-port