---
apiVersion: v1
kind: Deployment
metadata:
  name: rainbowdarkness-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rainbowdarkness-server
    spec:
      containers:
      - name: rainbowdarkness-server
        image: cayabyabrr/rainbowdarkness-server:latest
        resources:
          limits:
            cpu: "0.3"
            memory: "256Mi"
          requests:
            cpu: "0.3"
            memory: "128Mi"
        ports:
          - containerPort: 3002