apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rainbowdarkness-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: rainbowdarkness-server-port
      path: /metrics
  selector:
    matchLabels:
      app: rainbowdarkness-server-service-app