apiVersion: v1
kind: Service
metadata:
  name: stockshapes-server-service
  labels:
    job: stockshapes-server-service-job
    app: stockshapes-server-service-app
spec:
  selector:
    app: stockshapes-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 3001
      name: stockshapes-server-port