apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stockshapes-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 30s
      port: stockshapes-server-port
      path: /metrics
  selector:
    matchLabels:
      app: stockshapes-server-service-app