apiVersion: v1
kind: Deployment
metadata:
  name: stockshapes-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockshapes-server
    spec:
      containers:
      - name: stockshapes-server
        image: cayabyabrr/stockshapes-server:latest
        resources:
          limits:
            cpu: "0.3"
            memory: "256Mi"
          requests:
            cpu: "0.3"
            memory: "128Mi"
        ports:
          - containerPort: 3001